import { writeFileSync, mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { loadSandbox } from "../test/helpers/sandbox.mjs";
import { makePdf, SUMMARY_LINES } from "../test/helpers/synth.mjs";
import { BUILT, BUILT_URL, launch } from "./browser.mjs";
const ctx = loadSandbox(BUILT);
const dir = mkdtempSync(join(tmpdir(), "zone-"));
const p = join(dir, "Diagram Summary.pdf");
writeFileSync(p, makePdf(SUMMARY_LINES, ctx.fflate));
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 794, height: 480 } });
await page.goto(BUILT_URL);
await page.setInputFiles("#file", [p]);
await page.waitForFunction(() =>
  document.querySelector("#berth .berth-txt strong").textContent.includes("Summary loaded"));
await page.locator("#berth").scrollIntoViewIfNeeded();
await page.waitForTimeout(150);
await page.screenshot({ path: "tools/shot-7-zone.png" });
await browser.close();
console.log("zone shot done");
