import { BUILT_URL, launch } from "./browser.mjs";
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 794, height: 560 } });
await page.goto(BUILT_URL);
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(150);
await page.screenshot({ path: "tools/shot-5-lede.png" });
await page.locator("footer").scrollIntoViewIfNeeded();
await page.waitForTimeout(150);
await page.screenshot({ path: "tools/shot-6-smallprint.png" });
await browser.close();
console.log("copy shots done");
