/* SHEETS_HS_SKIN - the Class 395 Allocations Sheet's own dress, lifted
   from the operator's workbook by scratchpad/mkskin.py and renumbered
   into a minimal styleSheet. Layout and static house text only: no
   unit numbers, headcodes, dates or comments come with it. */
"use strict";
const SHEETS_HS_SKIN = {
 "stylesXml": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><numFmts count=\"2\"><numFmt numFmtId=\"165\" formatCode=\"dd/mm/yyyy;@\"/><numFmt numFmtId=\"167\" formatCode=\"h:mm;@\"/></numFmts><fonts count=\"22\"><font><sz val=\"11\"/><color theme=\"1\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF00B050\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color theme=\"1\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF0070C0\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF000000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF00B050\"/><name val=\"Calibri\"/></font><font><sz val=\"8\"/><color theme=\"1\"/><name val=\"Arial\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color theme=\"0\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF0070C0\"/><name val=\"Calibri\"/></font><font><sz val=\"16\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF000000\"/><name val=\"Calibri\"/></font><font><sz val=\"9\"/><name val=\"Arial\"/></font><font><b/><sz val=\"11\"/><color theme=\"1\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color theme=\"5\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"11\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"12\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><sz val=\"12\"/><name val=\"Calibri\"/></font><font><sz val=\"9\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"12\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"9\"/><color rgb=\"FF242424\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font><font><b/><sz val=\"14\"/><color rgb=\"FFFF0000\"/><name val=\"Calibri\"/><family val=\"2\"/><scheme val=\"minor\"/></font></fonts><fills count=\"10\"><fill><patternFill patternType=\"solid\"><fgColor theme=\"0\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"solid\"><fgColor theme=\"9\" tint=\"0.59999389629810485\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFFFFF00\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFFF0000\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF92D050\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF92D050\"/><bgColor rgb=\"FF000000\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF00B0F0\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF00B050\"/><bgColor indexed=\"64\"/></patternFill></fill><fill><patternFill patternType=\"solid\"><fgColor theme=\"0\" tint=\"-0.14999847407452621\"/><bgColor indexed=\"64\"/></patternFill></fill></fills><borders count=\"40\"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style=\"thin\"><color rgb=\"FF000000\"/></left><right style=\"thin\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"thin\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"thin\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"thin\"><color rgb=\"FF000000\"/></left><right style=\"thin\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"thin\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left/><right style=\"thin\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"thin\"><color rgb=\"FF000000\"/></left><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left/><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"thin\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top style=\"thin\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"thin\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"thin\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"thin\"><color indexed=\"64\"/></right><top style=\"medium\"><color indexed=\"64\"/></top><bottom style=\"thin\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left/><right style=\"thin\"><color indexed=\"64\"/></right><top/><bottom style=\"medium\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"thin\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color indexed=\"64\"/></left><right style=\"thin\"><color indexed=\"64\"/></right><top style=\"medium\"><color indexed=\"64\"/></top><bottom style=\"thin\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"medium\"><color indexed=\"64\"/></left><right style=\"thin\"><color indexed=\"64\"/></right><top/><bottom style=\"medium\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top/><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top style=\"medium\"><color rgb=\"FF000000\"/></top><bottom/><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top/><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right/><top/><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top/><bottom style=\"medium\"><color rgb=\"FF000000\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color indexed=\"64\"/></right><top/><bottom/><diagonal/></border><border><left/><right/><top style=\"medium\"><color indexed=\"64\"/></top><bottom style=\"thin\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"medium\"><color indexed=\"64\"/></top><bottom style=\"thin\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left/><right/><top style=\"thin\"><color indexed=\"64\"/></top><bottom style=\"medium\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top style=\"thin\"><color indexed=\"64\"/></top><bottom style=\"medium\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"thin\"><color indexed=\"64\"/></left><right/><top style=\"medium\"><color indexed=\"64\"/></top><bottom style=\"thin\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"thin\"><color indexed=\"64\"/></left><right/><top style=\"thin\"><color indexed=\"64\"/></top><bottom style=\"medium\"><color indexed=\"64\"/></bottom><diagonal/></border><border><left style=\"medium\"><color rgb=\"FF000000\"/></left><right/><top/><bottom/><diagonal/></border><border><left/><right style=\"medium\"><color rgb=\"FF000000\"/></right><top/><bottom/><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"103\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" applyFill=\"1\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"2\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"3\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"4\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"0\" borderId=\"4\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"5\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"4\" fillId=\"1\" borderId=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"0\" borderId=\"6\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"7\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"5\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"6\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"2\" borderId=\"8\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"2\" borderId=\"9\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"7\" fillId=\"3\" borderId=\"10\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"8\" fillId=\"4\" borderId=\"11\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"5\" borderId=\"12\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"5\" borderId=\"13\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"5\" fillId=\"0\" borderId=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"9\" fillId=\"1\" borderId=\"14\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"10\" fillId=\"1\" borderId=\"15\" quotePrefix=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"10\" fillId=\"1\" borderId=\"16\" quotePrefix=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"7\" fillId=\"3\" borderId=\"17\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"8\" fillId=\"4\" borderId=\"18\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"11\" fillId=\"6\" borderId=\"19\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"12\" fillId=\"4\" borderId=\"20\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"13\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"7\" borderId=\"21\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"8\" borderId=\"22\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"3\" borderId=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"14\" fillId=\"1\" borderId=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"20\" fontId=\"14\" fillId=\"1\" borderId=\"1\" applyNumberFormat=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"5\" fillId=\"0\" borderId=\"2\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"15\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"16\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"0\" fillId=\"9\" borderId=\"23\" applyFill=\"1\" applyBorder=\"1\"/><xf numFmtId=\"0\" fontId=\"0\" fillId=\"9\" borderId=\"0\" applyFill=\"1\"/><xf numFmtId=\"0\" fontId=\"11\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"7\" fillId=\"3\" borderId=\"14\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"10\" fillId=\"1\" borderId=\"0\" quotePrefix=\"1\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"18\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"4\" fillId=\"1\" borderId=\"24\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"4\" fillId=\"1\" borderId=\"25\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"4\" fillId=\"1\" borderId=\"26\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"27\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"8\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"9\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"27\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"28\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"29\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"30\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"27\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"8\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"9\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"28\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"29\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"30\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"11\" fillId=\"1\" borderId=\"27\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"11\" fillId=\"1\" borderId=\"9\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"11\" fillId=\"1\" borderId=\"28\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"11\" fillId=\"1\" borderId=\"30\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"13\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"18\" fillId=\"1\" borderId=\"27\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"18\" fillId=\"1\" borderId=\"9\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"24\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"25\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"1\" borderId=\"26\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"13\" fillId=\"1\" borderId=\"31\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"32\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"33\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"34\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"35\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"165\" fontId=\"20\" fillId=\"1\" borderId=\"28\" applyNumberFormat=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"165\" fontId=\"20\" fillId=\"1\" borderId=\"30\" applyNumberFormat=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"167\" fontId=\"2\" fillId=\"1\" borderId=\"28\" applyNumberFormat=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"167\" fontId=\"2\" fillId=\"1\" borderId=\"30\" applyNumberFormat=\"1\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"24\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"1\" borderId=\"26\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"24\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"25\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"26\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"24\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"25\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"1\" borderId=\"26\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"36\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"17\" fillId=\"1\" borderId=\"37\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"8\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"9\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"38\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"39\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"28\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"29\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"19\" fillId=\"1\" borderId=\"30\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"13\" fillId=\"1\" borderId=\"38\" applyFont=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"21\" fillId=\"1\" borderId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\" wrapText=\"1\"/></xf></cellXfs><cellStyles count=\"1\"><cellStyle name=\"Normal\" xfId=\"0\" builtinId=\"0\"/></cellStyles><dxfs count=\"2\"><dxf><font><b/><i val=\"0\"/><color theme=\"1\"/></font><fill><patternFill patternType=\"solid\"><bgColor theme=\"9\" tint=\"0.39997558519241921\"/></patternFill></fill></dxf><dxf><font><b/><i val=\"0\"/><color theme=\"0\"/></font><fill><patternFill patternType=\"solid\"><bgColor rgb=\"FFFF0000\"/></patternFill></fill></dxf></dxfs></styleSheet>",
 "colsXml": "<cols><col min=\"2\" max=\"2\" width=\"8.5703125\" customWidth=\"1\"/><col min=\"4\" max=\"4\" width=\"8.5703125\" customWidth=\"1\"/><col min=\"5\" max=\"6\" width=\"8.140625\" customWidth=\"1\"/><col min=\"8\" max=\"8\" width=\"8.5703125\" customWidth=\"1\"/><col min=\"9\" max=\"9\" width=\"8.140625\" customWidth=\"1\"/><col min=\"10\" max=\"10\" width=\"6.42578125\" customWidth=\"1\"/><col min=\"11\" max=\"11\" width=\"5.5703125\" customWidth=\"1\"/><col min=\"12\" max=\"12\" width=\"7.140625\" customWidth=\"1\"/><col min=\"13\" max=\"13\" width=\"6.28515625\" customWidth=\"1\"/><col min=\"14\" max=\"14\" width=\"7.28515625\" customWidth=\"1\"/><col min=\"15\" max=\"15\" width=\"8.28515625\" customWidth=\"1\"/><col min=\"16\" max=\"16\" width=\"7.7109375\" customWidth=\"1\"/><col min=\"17\" max=\"17\" width=\"7.85546875\" customWidth=\"1\"/><col min=\"18\" max=\"18\" width=\"7.7109375\" customWidth=\"1\"/></cols>",
 "tabColor": "FFFFFF00",
 "legend": [
  [
   1,
   "F",
   8,
   ""
  ],
  [
   1,
   "G",
   32,
   ""
  ],
  [
   1,
   "H",
   32,
   ""
  ],
  [
   1,
   "I",
   32,
   ""
  ],
  [
   1,
   "J",
   43,
   ""
  ],
  [
   1,
   "K",
   45,
   ""
  ],
  [
   1,
   "L",
   46,
   ""
  ],
  [
   1,
   "M",
   46,
   ""
  ],
  [
   1,
   "N",
   46,
   ""
  ],
  [
   1,
   "R",
   47,
   ""
  ],
  [
   1,
   "S",
   47,
   ""
  ],
  [
   2,
   "B",
   102,
   ""
  ],
  [
   2,
   "C",
   102,
   ""
  ],
  [
   2,
   "D",
   102,
   ""
  ],
  [
   2,
   "E",
   102,
   ""
  ],
  [
   2,
   "G",
   34,
   "INT CLEAN"
  ],
  [
   2,
   "H",
   101,
   "Mileage Guide"
  ],
  [
   2,
   "I",
   68,
   ""
  ],
  [
   2,
   "J",
   74,
   ""
  ],
  [
   2,
   "K",
   30,
   "\u00a0"
  ],
  [
   2,
   "L",
   26,
   "="
  ],
  [
   2,
   "M",
   91,
   "< 500 Miles"
  ],
  [
   2,
   "N",
   75,
   ""
  ],
  [
   2,
   "O",
   76,
   ""
  ],
  [
   2,
   "S",
   69,
   "Date Sent"
  ],
  [
   2,
   "T",
   70,
   ""
  ],
  [
   3,
   "A",
   40,
   ""
  ],
  [
   3,
   "B",
   102,
   ""
  ],
  [
   3,
   "C",
   102,
   ""
  ],
  [
   3,
   "D",
   102,
   ""
  ],
  [
   3,
   "E",
   102,
   ""
  ],
  [
   3,
   "G",
   33,
   "EXT CLEAN"
  ],
  [
   3,
   "H",
   101,
   ""
  ],
  [
   3,
   "I",
   68,
   ""
  ],
  [
   3,
   "J",
   74,
   ""
  ],
  [
   3,
   "K",
   31,
   "\u00a0"
  ],
  [
   3,
   "L",
   27,
   "="
  ],
  [
   3,
   "M",
   92,
   "> 500 Miles"
  ],
  [
   3,
   "N",
   77,
   ""
  ],
  [
   3,
   "O",
   78,
   ""
  ],
  [
   3,
   "S",
   79,
   ""
  ],
  [
   3,
   "T",
   80,
   ""
  ],
  [
   4,
   "B",
   40,
   ""
  ],
  [
   4,
   "C",
   40,
   ""
  ],
  [
   4,
   "D",
   40,
   ""
  ],
  [
   4,
   "E",
   40,
   ""
  ],
  [
   4,
   "S",
   69,
   "Time Sent"
  ],
  [
   4,
   "T",
   70,
   ""
  ],
  [
   5,
   "S",
   81,
   ""
  ],
  [
   5,
   "T",
   82,
   ""
  ],
  [
   6,
   "A",
   7,
   ""
  ],
  [
   6,
   "S",
   83,
   "VERSION 1"
  ],
  [
   6,
   "T",
   84,
   ""
  ]
 ],
 "legendHts": {
  "1": "21",
  "2": "21",
  "3": "21",
  "4": "15.75"
 },
 "footer": [
  [
   60,
   "A",
   7,
   ""
  ],
  [
   60,
   "B",
   48,
   "NOTE"
  ],
  [
   60,
   "C",
   49,
   ""
  ],
  [
   60,
   "D",
   49,
   ""
  ],
  [
   60,
   "E",
   49,
   ""
  ],
  [
   60,
   "F",
   50,
   ""
  ],
  [
   60,
   "H",
   88,
   "COMMENTS"
  ],
  [
   60,
   "I",
   89,
   ""
  ],
  [
   60,
   "J",
   89,
   ""
  ],
  [
   60,
   "K",
   89,
   ""
  ],
  [
   60,
   "L",
   89,
   ""
  ],
  [
   60,
   "M",
   89,
   ""
  ],
  [
   60,
   "N",
   89,
   ""
  ],
  [
   60,
   "O",
   89,
   ""
  ],
  [
   60,
   "P",
   89,
   ""
  ],
  [
   60,
   "Q",
   89,
   ""
  ],
  [
   60,
   "R",
   89,
   ""
  ],
  [
   60,
   "S",
   89,
   ""
  ],
  [
   60,
   "T",
   90,
   ""
  ],
  [
   61,
   "A",
   6,
   ""
  ],
  [
   61,
   "B",
   51,
   "FP AT ASHFORD IS STOPS END"
  ],
  [
   61,
   "C",
   52,
   ""
  ],
  [
   61,
   "D",
   52,
   ""
  ],
  [
   61,
   "E",
   52,
   ""
  ],
  [
   61,
   "F",
   53,
   ""
  ],
  [
   61,
   "H",
   54,
   ""
  ],
  [
   61,
   "I",
   93,
   ""
  ],
  [
   61,
   "J",
   93,
   ""
  ],
  [
   61,
   "K",
   93,
   ""
  ],
  [
   61,
   "L",
   93,
   ""
  ],
  [
   61,
   "M",
   93,
   ""
  ],
  [
   61,
   "N",
   93,
   ""
  ],
  [
   61,
   "O",
   93,
   ""
  ],
  [
   61,
   "P",
   93,
   ""
  ],
  [
   61,
   "Q",
   93,
   ""
  ],
  [
   61,
   "R",
   93,
   ""
  ],
  [
   61,
   "S",
   93,
   ""
  ],
  [
   61,
   "T",
   94,
   ""
  ],
  [
   62,
   "A",
   5,
   ""
  ],
  [
   62,
   "B",
   55,
   "FP AT RAMSGATE IS MARGATE END"
  ],
  [
   62,
   "C",
   56,
   ""
  ],
  [
   62,
   "D",
   56,
   ""
  ],
  [
   62,
   "E",
   56,
   ""
  ],
  [
   62,
   "F",
   57,
   ""
  ],
  [
   62,
   "H",
   95,
   ""
  ],
  [
   62,
   "I",
   96,
   ""
  ],
  [
   62,
   "J",
   96,
   ""
  ],
  [
   62,
   "K",
   96,
   ""
  ],
  [
   62,
   "L",
   96,
   ""
  ],
  [
   62,
   "M",
   96,
   ""
  ],
  [
   62,
   "N",
   96,
   ""
  ],
  [
   62,
   "O",
   96,
   ""
  ],
  [
   62,
   "P",
   96,
   ""
  ],
  [
   62,
   "Q",
   96,
   ""
  ],
  [
   62,
   "R",
   96,
   ""
  ],
  [
   62,
   "S",
   96,
   ""
  ],
  [
   62,
   "T",
   97,
   ""
  ],
  [
   63,
   "A",
   5,
   ""
  ],
  [
   63,
   "B",
   58,
   "Ramsgate arrivals. Units to be shown on the same line as their allocated diagram."
  ],
  [
   63,
   "C",
   59,
   ""
  ],
  [
   63,
   "D",
   59,
   ""
  ],
  [
   63,
   "E",
   59,
   ""
  ],
  [
   63,
   "F",
   60,
   ""
  ],
  [
   63,
   "H",
   95,
   ""
  ],
  [
   63,
   "I",
   96,
   ""
  ],
  [
   63,
   "J",
   96,
   ""
  ],
  [
   63,
   "K",
   96,
   ""
  ],
  [
   63,
   "L",
   96,
   ""
  ],
  [
   63,
   "M",
   96,
   ""
  ],
  [
   63,
   "N",
   96,
   ""
  ],
  [
   63,
   "O",
   96,
   ""
  ],
  [
   63,
   "P",
   96,
   ""
  ],
  [
   63,
   "Q",
   96,
   ""
  ],
  [
   63,
   "R",
   96,
   ""
  ],
  [
   63,
   "S",
   96,
   ""
  ],
  [
   63,
   "T",
   97,
   ""
  ],
  [
   64,
   "A",
   43,
   ""
  ],
  [
   64,
   "B",
   61,
   ""
  ],
  [
   64,
   "C",
   62,
   ""
  ],
  [
   64,
   "D",
   62,
   ""
  ],
  [
   64,
   "E",
   62,
   ""
  ],
  [
   64,
   "F",
   63,
   ""
  ],
  [
   64,
   "H",
   95,
   ""
  ],
  [
   64,
   "I",
   96,
   ""
  ],
  [
   64,
   "J",
   96,
   ""
  ],
  [
   64,
   "K",
   96,
   ""
  ],
  [
   64,
   "L",
   96,
   ""
  ],
  [
   64,
   "M",
   96,
   ""
  ],
  [
   64,
   "N",
   96,
   ""
  ],
  [
   64,
   "O",
   96,
   ""
  ],
  [
   64,
   "P",
   96,
   ""
  ],
  [
   64,
   "Q",
   96,
   ""
  ],
  [
   64,
   "R",
   96,
   ""
  ],
  [
   64,
   "S",
   96,
   ""
  ],
  [
   64,
   "T",
   97,
   ""
  ],
  [
   65,
   "A",
   43,
   ""
  ],
  [
   65,
   "B",
   64,
   "CET LEGEND"
  ],
  [
   65,
   "C",
   65,
   ""
  ],
  [
   65,
   "D",
   29,
   "5 DAYS +"
  ],
  [
   65,
   "E",
   28,
   "4 DAYS"
  ],
  [
   65,
   "F",
   22,
   "3 DAYS"
  ],
  [
   65,
   "H",
   95,
   ""
  ],
  [
   65,
   "I",
   96,
   ""
  ],
  [
   65,
   "J",
   96,
   ""
  ],
  [
   65,
   "K",
   96,
   ""
  ],
  [
   65,
   "L",
   96,
   ""
  ],
  [
   65,
   "M",
   96,
   ""
  ],
  [
   65,
   "N",
   96,
   ""
  ],
  [
   65,
   "O",
   96,
   ""
  ],
  [
   65,
   "P",
   96,
   ""
  ],
  [
   65,
   "Q",
   96,
   ""
  ],
  [
   65,
   "R",
   96,
   ""
  ],
  [
   65,
   "S",
   96,
   ""
  ],
  [
   65,
   "T",
   97,
   ""
  ],
  [
   66,
   "B",
   66,
   ""
  ],
  [
   66,
   "C",
   67,
   ""
  ],
  [
   66,
   "D",
   21,
   ""
  ],
  [
   66,
   "E",
   20,
   ""
  ],
  [
   66,
   "F",
   23,
   ""
  ],
  [
   66,
   "G",
   17,
   ""
  ],
  [
   66,
   "H",
   98,
   ""
  ],
  [
   66,
   "I",
   99,
   ""
  ],
  [
   66,
   "J",
   99,
   ""
  ],
  [
   66,
   "K",
   99,
   ""
  ],
  [
   66,
   "L",
   99,
   ""
  ],
  [
   66,
   "M",
   99,
   ""
  ],
  [
   66,
   "N",
   99,
   ""
  ],
  [
   66,
   "O",
   99,
   ""
  ],
  [
   66,
   "P",
   99,
   ""
  ],
  [
   66,
   "Q",
   99,
   ""
  ],
  [
   66,
   "R",
   99,
   ""
  ],
  [
   66,
   "S",
   99,
   ""
  ],
  [
   66,
   "T",
   100,
   ""
  ]
 ],
 "footerMerges": [
  "B60:F60",
  "H60:T60",
  "B61:F61",
  "H61:T66",
  "B62:F62",
  "B63:F64",
  "B65:C66"
 ],
 "title": {
  "A": 5,
  "B": 71,
  "C": 72,
  "D": 72,
  "E": 72,
  "F": 73,
  "G": 0,
  "H": 85,
  "I": 86,
  "J": 86,
  "K": 86,
  "L": 86,
  "M": 86,
  "N": 86,
  "O": 86,
  "P": 86,
  "Q": 86,
  "R": 86,
  "S": 86,
  "T": 87
 },
 "header": [
  [
   "A",
   16,
   ""
  ],
  [
   "B",
   9,
   "TRAIN ID"
  ],
  [
   "C",
   10,
   "ARRIVAL TIME"
  ],
  [
   "D",
   10,
   "UNIT NUMBER"
  ],
  [
   "E",
   10,
   "6 OR 12 CAR"
  ],
  [
   "F",
   15,
   "CET DUE"
  ],
  [
   "G",
   41,
   ""
  ],
  [
   "H",
   14,
   "TRAIN ID"
  ],
  [
   "I",
   11,
   "DIAGRAM"
  ],
  [
   "J",
   11,
   "N/M\r\nM/O"
  ],
  [
   "K",
   11,
   "MG"
  ],
  [
   "L",
   11,
   "TIME"
  ],
  [
   "M",
   11,
   "FP/RP"
  ],
  [
   "N",
   11,
   "UNIT NO"
  ],
  [
   "O",
   11,
   "ENDS AM"
  ],
  [
   "P",
   10,
   "ARRIVES"
  ],
  [
   "Q",
   10,
   "ENDS PM"
  ],
  [
   "R",
   10,
   "TRAIN ID"
  ],
  [
   "S",
   10,
   "ARRIVES"
  ],
  [
   "T",
   12,
   "WORKS"
  ]
 ],
 "headerHt": "24.75",
 "data": {
  "B": 38,
  "C": 24,
  "D": 13,
  "E": 13,
  "F": 44,
  "G": 42,
  "H": 2,
  "I": 3,
  "J": 1,
  "K": 35,
  "L": 3,
  "M": 3,
  "N": 4,
  "O": 36,
  "P": 37,
  "Q": 3,
  "R": 3,
  "S": 3,
  "T": 25
 },
 "greyRight": {
  "H": 18,
  "I": 18,
  "J": 18,
  "K": 18,
  "L": 18,
  "M": 18,
  "N": 18,
  "O": 18,
  "P": 18,
  "Q": 18,
  "R": 18,
  "S": 18,
  "T": 19
 },
 "gapRow": {
  "B": 39,
  "C": 39,
  "D": 39,
  "E": 39,
  "F": 39
 }
};
if (typeof module !== "undefined" && module.exports) module.exports = SHEETS_HS_SKIN;
if (typeof globalThis !== "undefined") globalThis.SHEETS_HS_SKIN = SHEETS_HS_SKIN;
